// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./components/AppAvatar.vue')['default']
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppTable: typeof import('./components/AppTable.vue')['default']
    AppTableUsers: typeof import('./components/AppTableUsers.vue')['default']
    CircleBorder: typeof import('./components/CircleBorder.vue')['default']
    copy: typeof import('./components/TheContent copy.vue')['default']
    GradientCircleBorder: typeof import('./components/GradientCircleBorder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBody: typeof import('./components/TheBody.vue')['default']
    TheContent: typeof import('./components/TheContent.vue')['default']
    TheContentLayout: typeof import('./components/TheContentLayout.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheHeaderAvatar: typeof import('./components/TheHeaderAvatar.vue')['default']
    TheLayout: typeof import('./components/TheLayout.vue')['default']
    TheLogo: typeof import('./components/TheLogo.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
    TheSidebarMain: typeof import('./components/TheSidebarMain.vue')['default']
    TheSidebarMainButton: typeof import('./components/TheSidebarMainButton.vue')['default']
    TheSidebarMainDecor: typeof import('./components/TheSidebarMainDecor.vue')['default']
    TheSidebarMenu: typeof import('./components/TheSidebarMenu.vue')['default']
    TheSidebarMenuWrap: typeof import('./components/TheSidebarMenuWrap.vue')['default']
    TheSidebarNav: typeof import('./components/TheSidebarNav.vue')['default']
    TheSidebarNavItem: typeof import('./components/TheSidebarNavItem.vue')['default']
    TheSidebarOverlay: typeof import('./components/TheSidebarOverlay.vue')['default']
    TheUsersTable: typeof import('./components/TheUsersTable.vue')['default']
    TheUserTable: typeof import('./components/TheUserTable.vue')['default']
    UserTable: typeof import('./components/UserTable.vue')['default']
  }
}
